//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./Auth_types');
//HELPER FUNCTIONS AND STRUCTURES

Auth_generateUrl_args = function(args) {
  this.redirectUrl = null;
  this.openid = null;
  if (args) {
    if (args.redirectUrl !== undefined && args.redirectUrl !== null) {
      this.redirectUrl = args.redirectUrl;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field redirectUrl is unset!');
    }
    if (args.openid !== undefined && args.openid !== null) {
      this.openid = args.openid;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field openid is unset!');
    }
  }
};
Auth_generateUrl_args.prototype = {};
Auth_generateUrl_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.redirectUrl = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.openid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Auth_generateUrl_args.prototype.write = function(output) {
  output.writeStructBegin('Auth_generateUrl_args');
  if (this.redirectUrl !== null && this.redirectUrl !== undefined) {
    output.writeFieldBegin('redirectUrl', Thrift.Type.STRING, 1);
    output.writeString(this.redirectUrl);
    output.writeFieldEnd();
  }
  if (this.openid !== null && this.openid !== undefined) {
    output.writeFieldBegin('openid', Thrift.Type.STRING, 2);
    output.writeString(this.openid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Auth_generateUrl_result = function(args) {
  this.success = null;
  this.err = null;
  if (args instanceof ttypes.InternalError) {
    this.err = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.err !== undefined && args.err !== null) {
      this.err = args.err;
    }
  }
};
Auth_generateUrl_result.prototype = {};
Auth_generateUrl_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.err = new ttypes.InternalError();
        this.err.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Auth_generateUrl_result.prototype.write = function(output) {
  output.writeStructBegin('Auth_generateUrl_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.err !== null && this.err !== undefined) {
    output.writeFieldBegin('err', Thrift.Type.STRUCT, 1);
    this.err.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AuthClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
AuthClient.prototype = {};
AuthClient.prototype.seqid = function() { return this._seqid; }
AuthClient.prototype.new_seqid = function() { return this._seqid += 1; }
AuthClient.prototype.generateUrl = function(redirectUrl, openid, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_generateUrl(redirectUrl, openid);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_generateUrl(redirectUrl, openid);
  }
};

AuthClient.prototype.send_generateUrl = function(redirectUrl, openid) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('generateUrl', Thrift.MessageType.CALL, this.seqid());
  var args = new Auth_generateUrl_args();
  args.redirectUrl = redirectUrl;
  args.openid = openid;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AuthClient.prototype.recv_generateUrl = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Auth_generateUrl_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.err) {
    return callback(result.err);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('generateUrl failed: unknown result');
};
AuthProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
AuthProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AuthProcessor.prototype.process_generateUrl = function(seqid, input, output) {
  var args = new Auth_generateUrl_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.generateUrl.length === 2) {
    Q.fcall(this._handler.generateUrl, args.redirectUrl, args.openid)
      .then(function(result) {
        var result = new Auth_generateUrl_result({success: result});
        output.writeMessageBegin("generateUrl", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.InternalError) {
          var result = new Auth_generateUrl_result(err);
          output.writeMessageBegin("generateUrl", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("generateUrl", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.generateUrl(args.redirectUrl, args.openid, function (err, result) {
      if (err == null || err instanceof ttypes.InternalError) {
        var result = new Auth_generateUrl_result((err != null ? err : {success: result}));
        output.writeMessageBegin("generateUrl", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("generateUrl", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

